"""Add is_current field to Experience model

Revision ID: 0eb23b0ac2ee
Revises: 4f36e9824abc
Create Date: 2024-07-07 21:01:32.826665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eb23b0ac2ee'
down_revision = '4f36e9824abc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experience', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_current', sa.Boolean(), nullable=False))

    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
        batch_op.alter_column('bio_title',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=25),
               nullable=False)
        batch_op.alter_column('github',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('linkedin',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.alter_column('linkedin',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('github',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('bio_title',
               existing_type=sa.String(length=25),
               type_=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)

    with op.batch_alter_table('experience', schema=None) as batch_op:
        batch_op.drop_column('is_current')

    # ### end Alembic commands ###
