"""Update profile table

Revision ID: 4f36e9824abc
Revises: 5de17bcb3ff7
Create Date: 2024-07-05 03:38:26.473624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f36e9824abc'
down_revision = '5de17bcb3ff7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(length=50), nullable=False),
    sa.Column('company_name', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('address', sa.String(length=1000), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
        batch_op.alter_column('bio_title',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.alter_column('github',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('linkedin',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.alter_column('linkedin',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('github',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('bio_title',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=25),
               nullable=False)
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    op.drop_table('experience')
    # ### end Alembic commands ###
