"""update picture

Revision ID: e190c3ffc10c
Revises: 1b69162754d0
Create Date: 2024-07-17 21:52:23.060798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e190c3ffc10c'
down_revision = '1b69162754d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture', sa.String(length=20), nullable=False))
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=20), nullable=False))
        batch_op.drop_column('picture')

    # ### end Alembic commands ###
